/*Competition*/
CREATE TABLE competition_data.COMPETITION (
	ID INTEGER,
	ORGANIZATION INTEGER NOT NULL,
	NAME character varying(50) NOT NULL,
	VIDEOGAME INTEGER NOT NULL,
	PLATFORM INTEGER NOT NULL,
	REGION INTEGER NOT NULL,
	GAMEMODE INTEGER NOT NULL,
	ENABLED BOOLEAN NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (ORGANIZATION) REFERENCES user_data.ORGANIZATION (ID),
	FOREIGN KEY (VIDEOGAME, PLATFORM) REFERENCES master_data.VIDEOGAME_PLATFORM (VIDEOGAME, PLATFORM),
	FOREIGN KEY (REGION) REFERENCES master_data.REGION (ID),
	FOREIGN KEY (GAMEMODE) REFERENCES master_data.GAMEMODE (ID)
);
